// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrungTamDaoTao.Data;

#nullable disable

namespace TrungTamDaoTao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250414131750_anhnguyendeptrai")]
    partial class anhnguyendeptrai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrungTamDaoTao.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHocVien", "MaKhoaHoc");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("DangKyKhoaHocs");
                });

            modelBuilder.Entity("TrungTamDaoTao.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("GiangVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuongHocVien")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHocVienHienTai")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianKhaiGiang")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("TrungTamDaoTao.Models.User", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isQuantrivien")
                        .HasColumnType("bit");

                    b.HasKey("MaHocVien");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("TrungTamDaoTao.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("TrungTamDaoTao.Models.User", "HocVien")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrungTamDaoTao.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("TrungTamDaoTao.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });

            modelBuilder.Entity("TrungTamDaoTao.Models.User", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
